org: thiagon4code
app: serverless-python-example
service: serverless-python-example

frameworkVersion: '1'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-offline
